import Head from 'next/head'
import { Inter } from 'next/font/google'
import Nav from '@/components/bar/navbar'
import Liste from '@/components/body/blueSubaru'
import SpainPhotos from '@/components/body/spainPhoto'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Espagne 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Nav/>
      <SpainPhotos/>
      </main>
    </>
  )
}
