import Head from 'next/head'
import { Inter } from 'next/font/google'
import MonBody from '@/components/body'
import NavIndex from '@/components/bar/navbarIndex'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <NavIndex/>
      <MonBody/>
      </main>
    </>
  )
}
